# Generated by Django 4.2.5 on 2023-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(max_length=255)),
                ('ameliorationChemin', models.CharField(max_length=255)),
                ('ameliorationNiveau', models.IntegerField(max_length=255)),
            ],
        ),
    ]
